onboarding = false
[ui.sound]
enabled = false

[ui]
show_agent_labels_on_pane_borders = true
sidebar_start_collapsed = true
sidebar_collapsed_mode = "compact"
# options "hidden" "compact"
mouse_capture = true
pane_borders = true
pane_gaps = false

[theme]
name = "catppuccin"
auto_switch = false

[keys]
reload_config = ["prefix+shift+r"]

# Navigation
# focus_pane_left = ["prefix+h", "ctrl+h"]
# focus_pane_right = ["prefix+l", "ctrl+l"]
# focus_pane_down = ["prefix+j", "ctrl+j"]
# focus_pane_up = ["prefix+k", "ctrl+k"]

# Activate resize mode
resize_mode = ["prefix+r", "alt+shift+h","alt+shift+j","alt+shift+k","alt+shift+l"]

# Sidebar
toggle_sidebar = ["prefix+b", "alt+shift+b"]

# Tabs
new_tab = ["prefix+c", "alt+n"]
next_tab = ["prefix+n"]
previous_tab = ["prefix+p"]
switch_tab = ["prefix+1..9", "alt+shift+1..9"] # Switch to tab 1..9

detach = ["prefix+q", "prefix+d"]

[experimental]
kitty_graphics = true


# Plugin Stuff
# herdr nvim navigation
[[keys.command]]
key = "ctrl+h"
type = "plugin_action"
command = "vim-herdr-navigation.left"
description = "navigate left (vim/herdr)"

[[keys.command]]
key = "ctrl+j"
type = "plugin_action"
command = "vim-herdr-navigation.down"
description = "navigate down (vim/herdr)"

[[keys.command]]
key = "ctrl+k"
type = "plugin_action"
command = "vim-herdr-navigation.up"
description = "navigate up (vim/herdr)"

[[keys.command]]
key = "ctrl+l"
type = "plugin_action"
command = "vim-herdr-navigation.right"
description = "navigate right (vim/herdr)"
